# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Accreditation Canada Style Guide
email: samuel.craymer@accreditation.ca
description: > # this means to ignore newlines until "baseurl:"
  Visual style guidelines and UI pattern library for Accreditation Canada
  software design and development.
baseurl: "/styleguide" # the subpath of your site, e.g. /blog
url: "https://accredcan.github.io" # the base hostname & protocol for your site
twitter_username: AccredCanada
github_username:  accredcan

# Build settings
markdown: kramdown
